
# Open Science for Music Research

This repository offers a guide to Open Science practices for music research, particularly aimed for music psychology and computational musicology, but also relevant for music information retrieval, music education, music technology, and musicology. 

## Reasons for creating this resource

In music research, there is room for improvement in _transparency_ and _reproducibility_, to widen the _accessibility_ and _equity_ with Open access to publications and data ensures that researchers, practitioners, and the public can benefit from scientific knowledge. Also, _innovation_ and _collaboration_ benefits from Open Science. A good teaching material dedicated to music research is missing at the moment and this repo attempts to fill this gap.

## The way this repository has been coordinated

This is a collaborative enterprise, where various authors contribute to specific sections and themes, see also @sec-preface.

- Tuomas Eerola (UK), see [Department of Music, Durham University](https://www.durham.ac.uk/staff/tuomas-eerola/)
- Johanna Devaney (US), see [Brooklyn College, CUNY](https://www.brooklyn.edu/faculty-staff/johanna-devaney/)
- Martin Hartmann (Finland), see [Centre of Excellence in Music, Mind, Body and Brain](https://www.jyu.fi/en/people/martin-hartmann)
- Dorien Herremans (Singapore), see [Audio, Music, and AI (AMAAI) Lab at Singapore University of Technology and Design](https://dorienherremans.com/biography)
- Fabian Moss (Germany), see [Institut für Musikforschung at Julius-Maximilians University Würzburg](https://fabian-moss.de)
- Jan Stupacher (Denmark), see [Center for Music in the Brain](https://fabian-moss.de)
- Hazel van der Walle (UK), see [Department of Music, Durham University](https://www.durham.ac.uk/staff/hazel-a-van-der-walle/)


## Organisation of the repository

- @sec-background explains the rationale and the broader picture

- @sec-OApubl covers the availability of research output and publications 

- @sec-OAdata handles the availability of research data 

- @sec-RR is about reproducible research, research code and software

- @sec-replication explains the purpose of replicating studies

- @sec-open-review covers open peer review and post-publication peer review

- @sec-registration details study preregistration

- @sec-resources offers links to online resources

