# Preface {.unnumbered, .unlisted, #sec-preface}

In music research, particularly for music psychology and computational musicology, we should have a repository of information about _Open Science_ and its all areas (open access publication, open data, open code, registration, and replication). Some of this information has been put together for journal articles [@moss2021fair;@jensenius2021best], but having a centralised starting point for this would be helpful for training and awareness.

The repository of information can be best done with collaborative writing and compiling the resources together. The contributors represent various sub-disciplines of music research (music psychology, computational musicology, MIR) and different countries (legal implications and academic practices).

## Plan and schedule

- Co-authors contacted and established (`February 2026`)
- Online repository coordinated at GitHub, potentially released at a dedicated domain address (not at [https://tuomaseerola.github.io](https://tuomaseerola.github.io))
- Early drafts ready (`November 2026`)
- Release (`February 2027`)
- Potential for a spin-off article and a hardcopy discussed (`Spring 2027`)

## Contributors (alphabetical) {#contributors}

- Tuomas Eerola (UK), see [Department of Music, Durham University](https://www.durham.ac.uk/staff/tuomas-eerola/)
- Johanna Devaney (US), see [Brooklyn College, CUNY](https://www.brooklyn.edu/faculty-staff/johanna-devaney/)
- Martin Hartmann (Finland), see [Centre of Excellence in Music, Mind, Body and Brain](https://www.jyu.fi/en/people/martin-hartmann)
- Dorien Herremans (Singapore), see [Audio, Music, and AI (AMAAI) Lab at Singapore University of Technology and Design](https://dorienherremans.com/biography)
- Fabian Moss (Germany), see [Institut für Musikforschung at Julius-Maximilians University Würzburg](https://fabian-moss.de)
- Jan Stupacher (Denmark), see [Center for Music in the Brain](https://fabian-moss.de)
- Hazel van der Walle (UK), see [Department of Music, Durham University](https://www.durham.ac.uk/staff/hazel-a-van-der-walle/)


## Writing guidelines

- Check [CONTRIBUTING.md](https://github.com/tuomaseerola/OSMR/blob/main/CONTRIBUTING.md) guide first.

- Using markdown text, including markdown references, e.g. `[@moss2021fair]` linked to `references.bib` file, and utilising within document links `@sec-background`. All implemented via [Quarto](https://quarto.org) documents at [GitHub](https://tuomaseerola.github.io/OSMR) to compile site/book as needed.

- Tracking the progress and issues via GitHub [Issues](https://github.com/tuomaseerola/OSMR/issues/).

- Authorship order to be determined based on contribution and made transparent with [Contributor Taxonomy](https://credit.niso.org).
