## Resources {#sec-resources}

A collection of resources related to open research. 

## Generic guides

- [Open Science: A Practical Guide for Early-Career Researchers](https://zenodo.org/records/7716153)
- [Awesome Reproducible Research](https://github.com/leipzig/awesome-reproducible-research)
- [Fairsharing](https://fairsharing.org)

## Preregistration services

- [AsPredicted](https://aspredicted.org/) and [templates](https://osf.io/zab38/files/fnsb6)
- [OSF Registries](https://osf.io/registries) and [templates](https://help.osf.io/article/330-welcome-to-registrations)
- [OSF registration templates](https://help.osf.io/article/229-select-a-registration-template) at OSF.
- [PROSPERO](https://www.crd.york.ac.uk/prospero/)
- [Registered Reports Center (COS)](https://www.cos.io/rr) [templates](https://osf.io/d4fh5/files/93znh)


## Tools

- Compare registration with papers, see [https://regcheck.app](https://regcheck.app)
- [rOpenSci](https://ropensci.org/) - Tools, conferences, and education
- [pyOpenSci](https://www.pyopensci.org/) - Promotes open and reproducible research through peer-review of scientific Python packages

## Organisations and networks

- [Open Science Framework](https://osf.io/) 
- [FORRT](https://forrt.org/) - Framework for Open and Reproducible Research Training advancing research transparency, reproducibility, rigor, and ethics through pedagogical reform and meta-scientific research
- [Reproducibility for Everyone](https://www.repro4everyone.org/) - Community-led reproducibility workshops
- [CASCaD](https://www.cascad.tech/) - Certification Agency for Scientific Code and Data
- [Replication Network](https://replicationnetwork.com/) - Furthering the practice of replication in economics.

## Music-specific resources

- [mirdata](https://mirdata.readthedocs.io/en/stable/) tools for working with common (MIR) datasets
- [MIR-Eval](https://mir-eval.readthedocs.io/latest/) transparent library for evaluating MIR systems
- [Best versus Good Enough Practices for Open Science in Music Research](https://emusicology.org/article/id/4788/)
- [Open Accessin Musicology](https://open-access.network/en/information/subject-specific-open-access/musicology)
- [Digital Resources for Musicology](https://drm.ccarh.org/)
- Example of [journal standards from Yearbook of Music Psychology](https://jbdgm.psychopen.eu/index.php/JBDGM/open-science)

